# Generated by Django 5.2.15 on 2026-06-08 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgroTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, help_text='Laissez vide : il sera généré automatiquement à partir du titre.', max_length=220, unique=True, verbose_name='Slug (URL)')),
                ('lieu', models.CharField(max_length=200, verbose_name='Lieu')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('prix', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Prix (FCFA)')),
                ('description_courte', models.CharField(help_text="Affichée sur les cartes de la page d'accueil.", max_length=300, verbose_name='Description courte')),
                ('description_complete', models.TextField(verbose_name='Description complète')),
                ('activites', models.TextField(blank=True, help_text='Une activité par ligne.', verbose_name='Activités réalisées')),
                ('image', models.ImageField(blank=True, null=True, upload_to='agrotrips/', verbose_name='Image principale (upload)')),
                ('image_url', models.URLField(blank=True, help_text="Utilisé si aucune image n'est uploadée.", verbose_name='Image principale (lien web)')),
                ('nombre_participants', models.PositiveIntegerField(default=0, verbose_name='Nombre de participants')),
                ('places_disponibles', models.PositiveIntegerField(default=20, help_text='Pour les AgroTrips à venir.', verbose_name='Places disponibles')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié')], default='publie', max_length=20, verbose_name='Statut de publication')),
                ('a_la_une', models.BooleanField(default=False, verbose_name="Mettre dans le slider d'accueil")),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'AgroTrip',
                'verbose_name_plural': 'AgroTrips',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=80, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=80, verbose_name='Nom')),
                ('telephone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('nombre_places', models.PositiveSmallIntegerField(default=1, verbose_name='Nombre de places')),
                ('message', models.TextField(blank=True, verbose_name='Message / besoin particulier')),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée')], default='nouvelle', max_length=20, verbose_name='Statut')),
                ('lu', models.BooleanField(default=False, verbose_name='Notification lue')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('agrotrip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='trips.agrotrip', verbose_name='AgroTrip choisi')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(max_length=120, verbose_name='Nom du participant')),
                ('texte', models.TextField(verbose_name='Témoignage')),
                ('note', models.PositiveSmallIntegerField(default=5, help_text='De 1 à 5 étoiles.', verbose_name='Note (sur 5)')),
                ('agrotrip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temoignages', to='trips.agrotrip')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
            },
        ),
        migrations.CreateModel(
            name='TripPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='galerie/', verbose_name='Image (upload)')),
                ('image_url', models.URLField(blank=True, verbose_name='Image (lien web)')),
                ('legende', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('agrotrip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='trips.agrotrip')),
            ],
            options={
                'verbose_name': 'Photo de galerie',
                'verbose_name_plural': 'Photos de galerie',
            },
        ),
    ]
