# Generated by Django 5.2.15 on 2026-06-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APropos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourquoi_titre', models.CharField(default='Pourquoi AgroTrip ?', max_length=200, verbose_name='Titre de la section Pourquoi')),
                ('pourquoi_texte', models.TextField(blank=True, help_text="Expliquez la raison d'être d'AgroTrip.", verbose_name="Texte d'explication (Pourquoi AgroTrip)")),
                ('mission_texte', models.TextField(blank=True, help_text="Décrivez la mission d'AgroTrip.", verbose_name='Notre mission')),
            ],
            options={
                'verbose_name': 'Page « Pourquoi AgroTrip »',
                'verbose_name_plural': 'Page « Pourquoi AgroTrip »',
            },
        ),
        migrations.CreateModel(
            name='Initiateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom complet')),
                ('role', models.CharField(blank=True, help_text='Ex : Fondatrice & CEO, Co-fondateur…', max_length=120, verbose_name='Rôle / Fonction')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='initiateurs/', verbose_name='Photo (upload)')),
                ('photo_url', models.URLField(blank=True, help_text="Utilisé si aucune photo n'est uploadée.", verbose_name='Photo (lien web)')),
                ('presentation', models.TextField(blank=True, verbose_name='Présentation')),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text='Les plus petits nombres apparaissent en premier.', verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Initiateur',
                'verbose_name_plural': 'Initiateurs',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom du partenaire')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partenaires/', verbose_name='Logo (upload)')),
                ('logo_url', models.URLField(blank=True, help_text="Utilisé si aucun logo n'est uploadé.", verbose_name='Logo (lien web)')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
