# Generated by Django 5.2.15 on 2026-06-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_apropos_initiateur_partenaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrotrip',
            name='prix_couple',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Forfait Couple (FCFA)'),
        ),
        migrations.AddField(
            model_name='agrotrip',
            name='prix_familiale',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Forfait Familiale (FCFA)'),
        ),
        migrations.AddField(
            model_name='agrotrip',
            name='prix_simple',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Forfait Simple (FCFA)'),
        ),
        migrations.AddField(
            model_name='registration',
            name='forfait',
            field=models.CharField(blank=True, choices=[('simple', 'Simple'), ('couple', 'Couple'), ('familiale', 'Familiale')], max_length=20, verbose_name='Forfait choisi'),
        ),
        migrations.AlterField(
            model_name='agrotrip',
            name='prix',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Prix affiché sur les cartes (à partir de).', max_digits=10, verbose_name='Prix indicatif (FCFA)'),
        ),
    ]
