# Generated by Django 5.2.15 on 2026-06-15 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_agrotrip_prix_couple_agrotrip_prix_familiale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(help_text='Collez un lien YouTube, Vimeo, ou un lien direct .mp4.', verbose_name='Lien de la vidéo')),
                ('titre', models.CharField(blank=True, max_length=200, verbose_name='Titre (facultatif)')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('agrotrip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='trips.agrotrip')),
            ],
            options={
                'verbose_name': 'Vidéo',
                'verbose_name_plural': 'Vidéos',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
